#!/usr/bin/env bash


# set some variables

homeDir=$HOME 
echo $homeDir

hostname=$HOSTNAME 
echo $hostname

os=$(lsb_release -d| awk '{print $2}') # definitely works on Fedora
echo $os


# ensure some directories exist
gitDir=$homeDir"/git"
[ ! -d $gitDir ] && mkdir -p $gitDir || echo $gitDir" already exists"

sshDir=$homeDir"/.ssh"
[ ! -d $sshDir ] && mkdir -p $sshDir || echo $sshDir" already exists"

configDir=$homeDir"/.config"
[ ! -d $configDir ] && mkdir -p $configDir || echo $configDir" already exists"


# create an ssh key, for use with git/github
ssh-keygen -t ed25519 -f $sshDir"/id_ed25519_git" -N ''


# check package manager
if [[ $os == "Ubuntu" ]]; then 
    echo "using apt package manager";
    sudo apt-get update && sudo apt-get upgrade;
    sudo apt install -y `cat apt-packages`;
    sudo snap install `cat snap-packages`;
    wget https://dl.discordapp.net/apps/linux/0.0.21/discord-0.0.21.deb;
    sudo apt install -f ./discord-0.0.21.deb;
elif [[ $os == "Fedora" ]]; then
    echo "dnf is not yet supported";
else
    echo "OS not yet supported";
fi 

cd $gitdir
gh auth login
# after logged into gh
gh repo list --limit 100 |awk '{print $1}'  | xargs -L1 gh repo clone
